run_env: local
docker_registry: ghcr.io/team-atlanta/test

oss_crs_infra:
  cpuset: "0-3"
  memory: "16G"

lacrosse-seed-gen:
  source:
    url: https://github.com/Team-Atlanta/lacrosse-seed-gen
    ref: main
  cpuset: "4-7"
  memory: "16G"
  llm_budget: 100

llm_config:
  litellm_config: ./example/lacrosse-seed-gen/litellm-config.yaml
