##############################################################################
#                    Azure E2E Config for crs-libfuzzer                      #
##############################################################################

run_env: azure
docker_registry: local

oss_crs_infra:
  cpuset: "0-1"
  memory: "4G"

crs-libfuzzer:
  cpuset: "2-3"
  memory: "8G"
